
import { RF, applyReforge } from '../src/lib/gt6_reforge.js'
import { gtBlock } from '../src/lib/gt6_materials.js'

const REMOVE = [
  'stellaris:titanium_ingot_from_smelting_ore',
  'stellaris:titanium_ingot_from_smelting_deepslate_ore',
  'stellaris:titanium_ingot_from_smelting_moon_ore',
  'stellaris:titanium_ingot_from_smelting_raw',
  'stellaris:titanium_ingot_from_blasting_ore',
  'stellaris:titanium_ingot_from_blasting_deepslate_ore',
  'stellaris:titanium_ingot_from_blasting_moon_ore',
  'stellaris:titanium_ingot_from_blasting_raw',
  'stellaris:titanium_ingot_from_block',
  'stellaris:titanium_ingot_from_nuggets',
  'stellaris:titanium_nugget_from_ingot',
]

const EDITS = [
  { id: 'stellaris:antenna', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:autopilot_module', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:big_black_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_black_can_from_black_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_blue_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_blue_can_from_blue_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_brown_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_brown_can_from_brown_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_cyan_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_cyan_can_from_cyan_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_gray_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_gray_can_from_gray_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_green_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_green_can_from_green_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_light_blue_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_light_blue_can_from_light_blue_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_light_gray_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_light_gray_can_from_light_gray_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_lime_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_lime_can_from_lime_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_magenta_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_magenta_can_from_magenta_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_orange_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_orange_can_from_orange_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_pink_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_pink_can_from_pink_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_purple_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_purple_can_from_purple_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_red_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_red_can_from_red_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_white_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_white_can_from_white_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_yellow_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:big_yellow_can_from_yellow_can', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:blender', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:blender', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:cargo_module', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:cargo_unloader', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:cargo_unloader', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:coal_generator', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:diesel_generator', path: 'key.i', value: RF.steel_plate },
  { id: 'stellaris:diesel_generator', path: 'key.s', value: RF.titanium_plate },
  { id: 'stellaris:electric_light', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:electrolyzer', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:electrolyzer', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:engine_fan', path: 'key.X', value: RF.titanium_plate },
  { id: 'stellaris:engineering_station', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:fluid_cell', path: 'key.S', value: RF.titanium_plate },
  { id: 'stellaris:fluid_tank_t1', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:fuel_refinery', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:fuel_refinery', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:gravity_manipulator', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:laboratory', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:oxygen_distributor', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:oxygen_propagator', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:pathogen_storage_cell', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:power_bank_t1', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:power_bank_t1', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:pumpjack', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:pumpjack', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[1]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[2]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[3]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[4]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[5]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[6]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[8]', value: RF.titanium_plate },
  { id: 'stellaris:rocket', path: 'ingredients[9]', value: RF.titanium_plate },
  { id: 'stellaris:rocket_engine', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:rocket_fin', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:rocket_nose_cone', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:rover', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:rover', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:small_rocket_model', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_farm', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_station_blueprint', path: 'ingredients[4]', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_boots', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_boots', path: 'key.T', value: RF.copper_plate },
  { id: 'stellaris:space_suit_chestplate', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_chestplate', path: 'key.T', value: RF.copper_plate },
  { id: 'stellaris:space_suit_damage_protection_module_tier_1', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:space_suit_damage_protection_module_tier_1', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_damage_protection_module_tier_2', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_damage_protection_module_tier_3', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_diesel_tank_module_tier_1', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_diesel_tank_module_tier_2', path: 'key.A', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_diesel_tank_module_tier_2', path: 'key.B', value: RF.steel_plate },
  { id: 'stellaris:space_suit_diesel_tank_module_tier_3', path: 'key.B', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_helmet', path: 'key.#', value: RF.copper_plate },
  { id: 'stellaris:space_suit_helmet', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_hydrogen_tank_module_tier_1', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_hydrogen_tank_module_tier_2', path: 'key.A', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_hydrogen_tank_module_tier_2', path: 'key.B', value: RF.steel_plate },
  { id: 'stellaris:space_suit_hydrogen_tank_module_tier_3', path: 'key.B', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_jet_module_tier_1', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_jet_module_tier_2', path: 'key.A', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_jet_module_tier_2', path: 'key.B', value: RF.steel_plate },
  { id: 'stellaris:space_suit_jet_module_tier_3', path: 'key.B', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_leggings', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_leggings', path: 'key.T', value: RF.copper_plate },
  { id: 'stellaris:space_suit_night_vision_module', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_oil_finder_module_tier_1', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_oil_finder_module_tier_2', path: 'key.A', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_oil_finder_module_tier_2', path: 'key.B', value: RF.steel_plate },
  { id: 'stellaris:space_suit_oil_finder_module_tier_3', path: 'key.B', value: RF.titanium_plate },
  { id: 'stellaris:space_suit_oxygen_module_tier_1', path: 'key.A', value: RF.steel_plate },
  { id: 'stellaris:space_suit_oxygen_module_tier_2', path: 'key.B', value: RF.titanium_plate },
  { id: 'stellaris:tablet', path: 'key.S', value: RF.titanium_plate },
  { id: 'stellaris:tiny_rocket_model', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:titanium_axe', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:titanium_block', path: 'key.#', value: RF.titanium_plate },
  { id: 'stellaris:titanium_hoe', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:titanium_nugget_from_ingot', path: 'ingredients[0]', value: RF.titanium_plate },
  { id: 'stellaris:titanium_pickaxe', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:titanium_shovel', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:titanium_sword', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:vacuumator', path: 'key.I', value: RF.steel_plate },
  { id: 'stellaris:vacuumator', path: 'key.T', value: RF.titanium_plate },
  { id: 'stellaris:water_pump', path: 'key.S', value: RF.titanium_plate },
]

const GATES = [
  { id: 'stellaris:coal_generator', path: 'pattern', value: ['#L#', '#X#', '#Z#'] },
  { id: 'stellaris:coal_generator', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:solar_panel', path: 'pattern', value: ['GGG', 'TTT', 'IZI'] },
  { id: 'stellaris:solar_panel', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:star_light_panel', path: 'pattern', value: ['OPO', 'DDD', 'IZI'] },
  { id: 'stellaris:star_light_panel', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:power_bank_t1', path: 'pattern', value: ['ITI', 'TRT', 'IZI'] },
  { id: 'stellaris:power_bank_t1', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:electrolyzer', path: 'pattern', value: ['CIC', 'BTB', 'TZT'] },
  { id: 'stellaris:electrolyzer', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:blender', path: 'pattern', value: ['TTT', 'IGI', 'TZT'] },
  { id: 'stellaris:blender',
    path: 'key',
    value: { "T": RF.titanium_plate,
      "G": "#c:glass_blocks/colorless",
      "I": RF.steel_plate,
      "Z": gtBlock('machineCasing', 'stainlesssteel')
    }
  },
  { id: 'stellaris:vacuumator', path: 'pattern', value: ['TGT', 'TRT', 'IZI'] },
  { id: 'stellaris:vacuumator',
    path: 'key',
    value: { "T": RF.titanium_plate,
      "G": "#c:glass_blocks/colorless",
      "R": "#c:dusts/redstone",
      "I": RF.steel_plate,
      "Z": gtBlock('machineCasing', 'stainlesssteel')
    }
  },
  { id: 'stellaris:oil_finder', path: 'pattern', value: [' X ', 'YSY', ' Z '] },
  { id: 'stellaris:oil_finder', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:laboratory', path: 'pattern', value: ['BTB', 'TCT', 'GZG'] },
  { id: 'stellaris:laboratory', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:space_farm', path: 'pattern', value: ['T T', 'TPT', 'TZT'] },
  { id: 'stellaris:space_farm',
    path: 'key',
    value: { "T": RF.titanium_plate,
      "P": "minecraft:flower_pot",
      "Z": gtBlock('machineCasing', 'stainlesssteel')
    }
  },
  { id: 'stellaris:pumpjack', path: 'pattern', value: ['TIT', 'IPI', 'SZS'] },
  { id: 'stellaris:pumpjack', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:cargo_unloader', path: 'pattern', value: ['TTT', 'IHI', 'TZT'] },
  { id: 'stellaris:cargo_unloader', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:oxygen_distributor', path: 'pattern', value: ['TTT', 'TFT', 'SZS'] },
  { id: 'stellaris:oxygen_distributor', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:oxygen_propagator', path: 'pattern', value: ['TTT', 'TFT', 'TZT'] },
  { id: 'stellaris:oxygen_propagator', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:gravity_manipulator', path: 'pattern', value: ['DTD', 'TRT', 'DZD'] },
  { id: 'stellaris:gravity_manipulator', path: 'key.Z', value: gtBlock('machineCasing', 'stainlesssteel') },
  { id: 'stellaris:diesel_generator', path: 'pattern', value: ['sss', 'ibi', 'iZi'] },
  { id: 'stellaris:diesel_generator',
    path: 'key',
    value: { "b": "#c:buckets/empty",
      "s": RF.titanium_plate,
      "i": RF.steel_plate,
      "Z": gtBlock('machineCasing', 'tungstensteel')
    }
  },
  { id: 'stellaris:fuel_refinery', path: 'pattern', value: ['BBT', 'IFI', 'TZT'] },
  { id: 'stellaris:fuel_refinery', path: 'key.Z', value: gtBlock('machineCasing', 'tungstensteel') },
  { id: 'stellaris:rocket_launch_pad', path: 'pattern', value: ['TTT', 'T T', 'TZT'] },
  { id: 'stellaris:rocket_launch_pad', path: 'key.Z', value: gtBlock('machineCasing', 'tungstensteel') },
  { id: 'stellaris:engineering_station', path: 'pattern', value: ['DTD', 'TCT', 'SZS'] },
  { id: 'stellaris:engineering_station', path: 'key.Z', value: gtBlock('machineCasing', 'tungstensteel') },
  { id: 'stellaris:rover', path: 'pattern', value: ['ICI', 'TWT', 'TZT'] },
  { id: 'stellaris:rover',
    path: 'key',
    value: { "I": RF.steel_plate,
      "C": "stellaris:cable_t1",
      "W": "#c:buckets/empty",
      "T": RF.titanium_plate,
      "Z": gtBlock('machineCasing', 'tungstensteel')
    }
  },
  { id: 'stellaris:hydrogen_motor', path: 'pattern', value: ['SSS', 'EDE', 'SZS'] },
  { id: 'stellaris:hydrogen_motor', path: 'key.Z', value: gtBlock('machineCasing', 'tungstensteel') },
  { id: 'stellaris:engine_fan', path: 'pattern', value: [' # ', '#X#', ' Z '] },
  { id: 'stellaris:engine_fan', path: 'key.Z', value: gtBlock('machineCasing', 'tungstensteel') },
  { id: 'stellaris:cable_t1', path: 'pattern', value: ['TTT', 'CCC', 'TZT'] },
  { id: 'stellaris:cable_t1', path: 'key.Z', value: RF.steel_plate },
  { id: 'stellaris:pipe_t1', path: 'pattern', value: ['TTT', 'GGG', 'TZT'] },
  { id: 'stellaris:pipe_t1', path: 'key.Z', value: RF.steel_plate },
  { id: 'stellaris:fluid_tank_t1', path: 'pattern', value: ['GGI', 'G G', 'IZI'] },
  { id: 'stellaris:fluid_tank_t1', path: 'key.Z', value: RF.steel_plate },
  { id: 'stellaris:antenna', path: 'pattern', value: ['RLR', 'TRT', 'SZS'] },
  { id: 'stellaris:antenna', path: 'key.Z', value: RF.steel_plate },
  { id: 'stellaris:sd_card', path: 'pattern', value: ['GSG', 'SRS', 'GZG'] },
  { id: 'stellaris:sd_card', path: 'key.Z', value: RF.steel_plate },
]

const ADD = []

ServerEvents.recipes(event => {
  applyReforge(event, { tag: 'Stellaris', remove: REMOVE, edits: EDITS, gates: GATES, add: ADD })
})
