import { GT_FORM, GT_BLOCK, GT_MATERIAL, gt, gtBlock, gtIngredient } from '../src/lib/gt6_materials.js'
import { modernizeRecipe } from '../src/lib/gt6_ingredient_forms.js'

const REMOVE = [
  'ae2:decorative/light_detector',
  'ae2:decorative/quartz_fixture',
  'ae2:decorative/quartz_fixture_from_anchors',
  'ae2:decorative/quartz_glass',
  'ae2:materials/advancedcard',
  'ae2:materials/annihilationcore',
  'ae2:materials/basiccard',
  'ae2:materials/cardcapacity',
  'ae2:materials/cardcrafting',
  'ae2:materials/cardinverter',
  'ae2:materials/cardredstone',
  'ae2:materials/cardspeed',
  'ae2:materials/formationcore',
  'ae2:network/blocks/cell_workbench',
  'ae2:network/blocks/controller',
  'ae2:network/blocks/crystal_processing_charger',
  'ae2:network/blocks/energy_dense_energy_cell',
  'ae2:network/blocks/energy_energy_acceptor',
  'ae2:network/blocks/energy_energy_acceptor_alt',
  'ae2:network/blocks/energy_energy_cell',
  'ae2:network/blocks/interfaces_interface',
  'ae2:network/blocks/io_condenser',
  'ae2:network/blocks/io_port',
  'ae2:network/blocks/quantum_link',
  'ae2:network/blocks/quantum_ring',
  'ae2:network/blocks/spatial_io_port',
  'ae2:network/blocks/spatial_io_pylon',
  'ae2:network/blocks/storage_chest',
  'ae2:network/blocks/storage_drive',
  'ae2:network/cables/covered_fluix',
  'ae2:network/cables/covered_fluix_clean',
  'ae2:network/cables/glass_fluix',
  'ae2:network/cables/glass_fluix_clean',
  'ae2:network/cells/fluid_cell_housing',
  'ae2:network/cells/fluid_storage_cell_16k',
  'ae2:network/cells/fluid_storage_cell_16k_storage',
  'ae2:network/cells/fluid_storage_cell_1k',
  'ae2:network/cells/fluid_storage_cell_1k_storage',
  'ae2:network/cells/fluid_storage_cell_256k',
  'ae2:network/cells/fluid_storage_cell_256k_storage',
  'ae2:network/cells/fluid_storage_cell_4k',
  'ae2:network/cells/fluid_storage_cell_4k_storage',
  'ae2:network/cells/fluid_storage_cell_64k',
  'ae2:network/cells/fluid_storage_cell_64k_storage',
  'ae2:network/cells/item_cell_housing',
  'ae2:network/cells/item_storage_cell_16k',
  'ae2:network/cells/item_storage_cell_16k_storage',
  'ae2:network/cells/item_storage_cell_1k',
  'ae2:network/cells/item_storage_cell_1k_storage',
  'ae2:network/cells/item_storage_cell_256k',
  'ae2:network/cells/item_storage_cell_256k_storage',
  'ae2:network/cells/item_storage_cell_4k',
  'ae2:network/cells/item_storage_cell_4k_storage',
  'ae2:network/cells/item_storage_cell_64k',
  'ae2:network/cells/item_storage_cell_64k_storage',
  'ae2:network/cells/item_storage_components_cell_16k_part',
  'ae2:network/cells/item_storage_components_cell_1k_part',
  'ae2:network/cells/item_storage_components_cell_256k_part',
  'ae2:network/cells/item_storage_components_cell_4k_part',
  'ae2:network/cells/item_storage_components_cell_64k_part',
  'ae2:network/cells/spatial_components',
  'ae2:network/cells/spatial_components_0',
  'ae2:network/cells/spatial_components_1',
  'ae2:network/cells/spatial_storage_cell_128_cubed',
  'ae2:network/cells/spatial_storage_cell_128_cubed_storage',
  'ae2:network/cells/spatial_storage_cell_16_cubed',
  'ae2:network/cells/spatial_storage_cell_16_cubed_storage',
  'ae2:network/cells/spatial_storage_cell_2_cubed',
  'ae2:network/cells/spatial_storage_cell_2_cubed_storage',
  'ae2:network/cells/view_cell',
  'ae2:network/cells/view_cell_storage',
  'ae2:network/crafting/cpu_crafting_accelerator',
  'ae2:network/crafting/cpu_crafting_monitor',
  'ae2:network/crafting/cpu_crafting_unit',
  'ae2:network/crafting/molecular_assembler',
  'ae2:network/crafting/patterns_blank',
  'ae2:network/parts/annihilation_plane_alt',
  'ae2:network/parts/annihilation_plane_alt2',
  'ae2:network/parts/export_bus',
  'ae2:network/parts/formation_plane',
  'ae2:network/parts/formation_plane_alt',
  'ae2:network/parts/import_bus',
  'ae2:network/parts/level_emitter',
  'ae2:network/parts/monitors_conversion',
  'ae2:network/parts/monitors_storage',
  'ae2:network/parts/panels_semi_dark_monitor',
  'ae2:network/parts/panels_semi_dark_monitor_alt',
  'ae2:network/parts/storage_bus',
  'ae2:network/parts/terminals',
  'ae2:network/parts/terminals_crafting',
  'ae2:network/parts/terminals_pattern_access',
  'ae2:network/parts/terminals_pattern_encoding',
  'ae2:network/parts/tunnels_me',
  'ae2:network/wireless_access_point',
  'ae2:network/wireless_booster',
  'ae2:network/wireless_part',
  'ae2:network/wireless_terminal',
  'ae2:tools/certus_quartz_cutting_knife',
  'ae2:tools/nether_quartz_cutting_knife',
  'ae2:tools/network_color_applicator',
  'ae2:tools/network_memory_card',
  'ae2:tools/network_tool',
  'ae2:tools/portable_fluid_cell_1k',
  'ae2:tools/portable_item_cell_1k',
  'extendedae:assembler/wireless_connector',
  'extendedae:assembler/wireless_hub',
  'extendedae:ingredient_buffer',
  'extendedae:void_cell',
  'ae2:network/blocks/pattern_providers_interface',
  'ae2:charger/meteorite_compass',
  'ae2:materials/cardfuzzy',
  'ae2:network/crystal_resonance_generator',
  'ae2:network/blocks/crank',
  'ae2:network/blocks/crystal_processing_growth_accelerator',
  'ae2:network/blocks/inscribers',
  'ae2:network/parts/cable_anchor',
  'ae2:network/parts/energy_acceptor',
  'ae2:network/parts/energy_level_emitter',
  'ae2:network/parts/panels_dark_monitor',
  'ae2:network/parts/panels_monitor',
  'ae2:network/parts/toggle_bus_inverted_alt',
  'ae2:tools/certus_quartz_axe',
  'ae2:tools/certus_quartz_hoe',
  'ae2:tools/certus_quartz_pickaxe',
  'ae2:tools/certus_quartz_spade',
  'ae2:tools/certus_quartz_sword',
  'ae2:tools/certus_quartz_wrench',
  'ae2:tools/fluix_axe',
  'ae2:tools/fluix_hoe',
  'ae2:tools/fluix_pickaxe',
  'ae2:tools/fluix_shovel',
  'ae2:tools/fluix_sword',
  'ae2:tools/fluix_upgrade_smithing_template',
  'ae2:tools/matter_cannon',
  'ae2:tools/misctools_charged_staff',
  'ae2:tools/misctools_entropy_manipulator',
  'ae2:tools/nether_quartz_axe',
  'ae2:tools/nether_quartz_hoe',
  'ae2:tools/nether_quartz_pickaxe',
  'ae2:tools/nether_quartz_spade',
  'ae2:tools/nether_quartz_sword',
  'ae2:tools/nether_quartz_wrench',
]

const RECIPES = [
{ id: 'nekojs:ae2/medrive',
      result: 'ae2:drive',
      pattern: ['aba', 'c c', 'fdg'],
      keys: {
      a: gt('plate', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:fluix_glass_cable',
      d: gtBlock('machineCasing', 'aluminium'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/mechest',
      result: 'ae2:me_chest',
      pattern: ['abc', 'ded', 'ihj'],
      keys: {
      a: gt('wire', 'copper'),
      b: 'ae2:terminal',
      c: gt('screw', 'steel'),
      d: 'ae2:fluix_glass_cable',
      e: 'minecraft:chest',
      h: gtBlock('machineCasing', 'aluminium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/mecontroller',
      result: 'ae2:controller',
      pattern: ['aba', 'e e', 'fcg'],
      keys: {
      a: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      b: 'ae2:engineering_processor',
      c: gtBlock('machineCasing', 'aluminium'),
      e: gtIngredient('gregtech:gt.multiitem.technological', 12101),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      } },
{ id: 'nekojs:ae2/energycell',
      result: 'ae2:energy_cell',
      pattern: ['aba', 'b b', 'gch'],
      keys: {
      a: gt('screw', 'galvanizedsteel'),
      b: 'enderio:basic_capacitor',
      c: gtBlock('machineCasing', 'galvanizedsteel'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12002),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12082),
      } },
{ id: 'nekojs:ae2/denseenergycell',
      result: 'ae2:dense_energy_cell',
      pattern: ['aba', 'bcb', 'hgi'],
      keys: {
      a: gt('screw', 'galvanizedsteel'),
      b: 'enderio:double_layer_capacitor',
      c: 'ae2:energy_cell',
      g: gtBlock('machineCasing', 'galvanizedsteel'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12002),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12082),
      } },
{ id: 'nekojs:ae2/energyacceptor',
      result: 'ae2:energy_acceptor',
      pattern: ['aba', 'c c', 'fdg'],
      keys: {
      a: 'ae2:fluix_glass_cable',
      b: gt('wire', 'copper'),
      c: gt('wire', 'copper', 2),
      d: gtBlock('machineCasing', 'galvanizedsteel'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12002),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12042),
      } },
{ id: 'nekojs:ae2/meinterfaceblock',
      result: 'ae2:interface',
      pattern: ['aba', 'c e', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:formation_core',
      d: gtBlock('machineCasing', 'aluminium'),
      e: 'ae2:annihilation_core',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/meioport',
      result: 'ae2:io_port',
      pattern: ['aba', 'cdc', 'gfh'],
      keys: {
      a: gt('plate', 'aluminium'),
      b: gt('screw', 'steel'),
      c: 'ae2:drive',
      d: 'ae2:fluix_glass_cable',
      f: gtBlock('machineCasing', 'aluminium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/craftingunit',
      result: 'ae2:crafting_unit',
      pattern: ['aba', 'c c', 'hdi'],
      keys: {
      a: 'ae2:calculation_processor',
      b: 'ae2:logic_processor',
      c: 'ae2:fluix_glass_cable',
      d: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12044),
      } },
{ id: 'nekojs:ae2/craftingcoprocessingunit',
      result: 'ae2:crafting_accelerator',
      pattern: ['abc', 'ded', 'hgi'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'extendedae:concurrent_processor',
      c: gt('screw', 'titanium'),
      d: 'ae2:engineering_processor',
      e: 'ae2:crafting_unit',
      g: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12044),
      } },
{ id: 'nekojs:ae2/craftingmonitor',
      result: 'ae2:crafting_monitor',
      pattern: ['abc', 'cde', 'gfh'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:crafting_unit',
      c: gt('screw', 'titanium'),
      d: 'ae2:storage_monitor',
      e: gt('screw', 'steel'),
      f: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/molecularassembler',
      result: 'ae2:molecular_assembler',
      pattern: ['aba', 'cdc', 'hgi'],
      keys: {
      a: 'ae2:quartz_glass',
      b: 'ae2:annihilation_core',
      c: 'ae2:formation_core',
      d: 'ae2:formation_core',
      g: gtBlock('machineCasing', 'tungsten'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12005),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12145),
      } },
{ id: 'nekojs:ae2/mequantumring',
      result: 'ae2:quantum_ring',
      pattern: ['abc', 'd d', 'hei'],
      keys: {
      a: gt('wire', 'copper'),
      b: 'ae2:engineering_processor',
      c: 'ae2:fluix_covered_cable',
      d: 'ae2:logic_processor',
      e: gtBlock('machineCasing', 'tungsten'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12105),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12145),
      } },
{ id: 'nekojs:ae2/mequantumlinkchamber',
      result: 'ae2:quantum_link',
      pattern: ['abc', 'bdb', 'hgi'],
      keys: {
      a: gt('plate', 'tungstensteel'),
      b: 'ae2:fluix_pearl',
      c: gt('ingot', 'redalloy'),
      d: 'ae2:quartz_glass',
      g: gtBlock('machineCasing', 'aluminium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12101),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      } },
{ id: 'nekojs:ae2/mattercondenser',
      result: 'ae2:condenser',
      pattern: ['aba', 'c c', 'fdg'],
      keys: {
      a: gt('plate', 'aluminium'),
      b: gt('screw', 'steel'),
      c: 'minecraft:piston',
      d: gtBlock('machineCasing', 'tungsten'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12025),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12045),
      } },
{ id: 'nekojs:ae2/spatialpylon',
      result: 'ae2:spatial_pylon',
      pattern: ['aba', 'cdc', 'gfh'],
      keys: {
      a: gt('plate', 'titanium'),
      b: 'ae2:fluix_glass_cable',
      c: 'ae2:fluix_dust',
      d: 'ae2:fluix_crystal',
      f: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12104),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      } },
{ id: 'nekojs:ae2/spatialioport',
      result: 'ae2:spatial_io_port',
      pattern: ['aba', 'cdc', 'gfh'],
      keys: {
      a: gt('plate', 'titanium'),
      b: 'ae2:quartz_glass',
      c: 'ae2:fluix_glass_cable',
      d: 'ae2:io_port',
      f: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12084),
      } },
{ id: 'nekojs:ae2/cellworkbench',
      result: 'ae2:cell_workbench',
      pattern: ['abc', 'd d', 'geh'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:calculation_processor',
      c: gt('screw', 'titanium'),
      d: gt('plate', 'aluminium'),
      e: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12084),
      } },
{ id: 'nekojs:ae2/wirelesshub',
      result: 'extendedae:wireless_hub',
      pattern: ['aaa', 'aba', 'gfh'],
      keys: {
      a: 'extendedae:wireless_connect',
      b: 'ae2:wireless_receiver',
      f: gtBlock('machineCasing', 'aluminium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      } },
{ kind: 'shapeless', id: 'nekojs:ae2/wirelessconnector_alt2',
      result: 'extendedae:wireless_connect',
      ingredients: [
        'extendedae:wireless_connect',
        gtIngredient('gregtech:gt.multiitem.technological', 12001),
        gtIngredient('gregtech:gt.multiitem.technological', 12041),
      ] },
{ id: 'nekojs:ae2/patternprovider',
      result: 'ae2:pattern_provider',
      pattern: ['aba', 'cfe', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:blank_pattern',
      d: gtBlock('machineCasing', 'aluminium'),
      e: 'ae2:logic_processor',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/mestoragebus',
      result: 'ae2:storage_bus',
      pattern: ['aba', 'cdc', 'hif'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: gt('screw', 'steel'),
      c: 'minecraft:piston',
      d: 'ae2:cable_interface',
      f: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      i: gtBlock('machineCasing', 'aluminium'),
      } },
{ id: 'nekojs:ae2/meimportbus',
      result: 'ae2:import_bus',
      pattern: ['abc', 'ded', 'ihj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:annihilation_core',
      c: 'ae2:fluix_glass_cable',
      d: gt('plate', 'aluminium'),
      e: 'minecraft:piston',
      h: gtBlock('machineCasing', 'aluminium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      } },
{ id: 'nekojs:ae2/meexportbus',
      result: 'ae2:export_bus',
      pattern: ['abc', 'ded', 'ihj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:formation_core',
      c: 'ae2:fluix_glass_cable',
      d: gt('plate', 'aluminium'),
      e: 'minecraft:piston',
      h: gtBlock('machineCasing', 'aluminium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      } },
{ id: 'nekojs:ae2/p2ptunnel',
      result: 'ae2:me_p2p_tunnel',
      pattern: ['abc', 'ded', 'ihj'],
      keys: {
      a: gt('screw', 'titanium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:fluix_glass_cable',
      d: gt('plate', 'titanium'),
      e: 'ae2:fluix_crystal',
      h: gtBlock('machineCasing', 'titanium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12044),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      } },
{ id: 'nekojs:ae2/meformationplane',
      result: 'ae2:formation_plane',
      pattern: ['aaa', 'bcb', 'gfh'],
      keys: {
      a: 'ae2:fluix_crystal',
      b: gt('plate', 'tungsten'),
      c: 'ae2:formation_core',
      f: gtBlock('machineCasing', 'tungsten'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12005),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12045),
      } },
{ id: 'nekojs:ae2/meannihilationplane',
      result: 'ae2:annihilation_plane',
      pattern: ['aaa', 'bcb', 'gfh'],
      keys: {
      a: 'ae2:fluix_crystal',
      b: gt('plate', 'tungsten'),
      c: 'ae2:annihilation_core',
      f: gtBlock('machineCasing', 'tungsten'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12005),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12045),
      } },
{ id: 'nekojs:ae2/meterminal',
      result: 'ae2:terminal',
      pattern: ['hab', 'cde', 'kjl'],
      keys: {
      a: 'ae2:logic_processor',
      b: 'ae2:fluix_glass_cable',
      c: 'ae2:formation_core',
      d: 'ae2:semi_dark_monitor',
      e: 'ae2:annihilation_core',
      h: gtIngredient('gregtech:gt.multiitem.technological', 12021),
      j: gtBlock('machineCasing', 'aluminium'),
      k: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      l: gtIngredient('gregtech:gt.multiitem.technological', 12121),
      } },
{ id: 'nekojs:ae2/mecraftingterminal',
      result: 'ae2:crafting_terminal',
      pattern: ['aba', 'aca', 'hgi'],
      keys: {
      a: gt('screw', 'titanium'),
      b: 'ae2:terminal',
      c: 'minecraft:crafting_table',
      g: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/mepatternterminal',
      result: 'ae2:pattern_encoding_terminal',
      pattern: ['aba', 'aca', 'hgi'],
      keys: {
      a: gt('screw', 'titanium'),
      b: 'ae2:terminal',
      c: 'ae2:blank_pattern',
      g: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/meprocessingpatternterminal',
      result: 'ae2:pattern_access_terminal',
      pattern: ['aba', 'cde', 'ihj'],
      keys: {
      a: gt('screw', 'titanium'),
      b: 'ae2:terminal',
      c: 'ae2:calculation_processor',
      d: 'ae2:engineering_processor',
      e: 'ae2:logic_processor',
      h: gtBlock('machineCasing', 'titanium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/mestoragemonitor',
      result: 'ae2:storage_monitor',
      pattern: ['aba', 'cde', 'gfh'],
      keys: {
      a: gt('screw', 'titanium'),
      b: 'ae2:level_emitter',
      c: gt('screw', 'steel'),
      d: 'ae2:semi_dark_monitor',
      e: gt('screw', 'steel'),
      f: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/meconversionmonitor',
      result: 'ae2:conversion_monitor',
      pattern: ['abc', 'def', 'ihj'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:level_emitter',
      c: gt('screw', 'titanium'),
      d: 'ae2:annihilation_core',
      e: 'ae2:storage_monitor',
      f: 'ae2:formation_core',
      h: gtBlock('machineCasing', 'titanium'),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/mewirelessaccesspoint',
      result: 'ae2:wireless_access_point',
      pattern: ['abc', 'ded', 'jik'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:wireless_receiver',
      c: 'ae2:fluix_glass_cable',
      d: gt('screw', 'tungsten'),
      e: gt('casingSmall', 'tungsten'),
      i: gtBlock('machineCasing', 'tungsten'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12005),
      k: gtIngredient('gregtech:gt.multiitem.technological', 12045),
      } },
{ id: 'nekojs:ae2/illuminatedpanel',
      result: 'ae2:semi_dark_monitor',
      pattern: ['fab', 'cab', 'hgi'],
      keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:quartz_vibrant_glass',
      c: 'ae2:fluix_glass_cable',
      f: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      g: gtBlock('machineCasing', 'aluminium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12121),
      } },
{ id: 'nekojs:ae2/melevelemitter',
      result: 'ae2:level_emitter',
      pattern: ['fag', 'bcd', 'jki'],
      keys: {
      a: 'minecraft:redstone_torch',
      b: gt('screw', 'steel'),
      c: 'ae2:calculation_processor',
      d: gt('gearSmall', 'steel'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12061),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12121),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      k: gtBlock('machineCasing', 'aluminium'),
      } },
{ id: 'nekojs:ae2/chargedquartzfixture',
    result: 'ae2:quartz_fixture',
    pattern: ['ab', 'c '],
    keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:certus_quartz_crystal',
      c: gt('stick', 'iron'),
    } },
{ id: 'nekojs:ae2/lightdetectingfixture',
      result: 'ae2:light_detector',
      pattern: ['ab', 'cf'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'minecraft:quartz',
      c: gt('stick', 'iron'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12101),
      } },
{ id: 'nekojs:ae2/networktool',
      result: 'ae2:network_tool',
      pattern: ['abc', 'fdg', 'hjg'],
      keys: {
      a: gt('screw', 'steel'),
      b: gt('screw', 'steel'),
      c: gt('screw', 'aluminium'),
      d: 'ae2:semi_dark_monitor',
      f: gtIngredient('gregtech:gt.multiitem.technological', 12121),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      j: gtBlock('machineCasing', 'aluminium'),
      } },
{ id: 'nekojs:ae2/colorapplicator',
      result: 'ae2:color_applicator',
      pattern: ['abf', 'bcg', 'gjf'],
      keys: {
      a: 'ae2:formation_core',
      b: gt('stick', 'aluminium'),
      c: 'ae2:cell_component_4k',
      f: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      j: gtBlock('machineCasing', 'aluminium'),
      } },
{ id: 'nekojs:ae2/fluixcable',
    result: 'ae2:fluix_glass_cable', count: 4,
    pattern: [' a ', 'aba', ' a '],
    keys: {
      a: 'ae2:quartz_fiber',
      b: 'ae2:fluix_dust',
    } },
{ kind: 'shapeless', id: 'nekojs:ae2/coveredfluixcable',
    result: 'ae2:fluix_covered_cable',
    ingredients: [
      'ae2:fluix_glass_cable',
      gt('plate', 'rubber'),
    ] },
{ id: 'nekojs:ae2/blankpattern',
    result: 'ae2:blank_pattern',
    pattern: [' ab', 'cdc', 'bef'],
    keys: {
      a: gt('plate', 'plastic'),
      b: gt('screw', 'plastic'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:quartz_glass',
      e: gt('casingSmall', 'plastic'),
      f: gt('screw', 'steel'),
    } },
{ id: 'nekojs:ae2/portablecell',
    result: 'ae2:portable_item_cell_1k',
    pattern: ['ab ', 'cdc', ' ef'],
    keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:item_storage_cell_1k',
      c: gt('screw', 'titanium'),
      d: 'ae2:me_chest',
      e: 'ae2:energy_cell',
      f: gt('screw', 'steel'),
    } },
{ id: 'nekojs:ae2/voidstoragecell',
    result: 'extendedae:void_cell',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: 'minecraft:ender_eye',
      c: gt('dust', 'redalloy'),
      d: 'ae2:singularity',
      e: gt('screw', 'titanium'),
      f: gt('plate', 'titanium'),
    } },
{ id: 'nekojs:ae2/storagecell1k',
    result: 'ae2:item_storage_cell_1k',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:cell_component_1k',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/storagecell4k',
    result: 'ae2:item_storage_cell_4k',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:cell_component_4k',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/storagecell16k',
    result: 'ae2:item_storage_cell_16k',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:cell_component_16k',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/storagecell64k',
    result: 'ae2:item_storage_cell_64k',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:cell_component_64k',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ kind: 'shapeless', id: 'nekojs:ae2/storagecell256k_alt2',
    result: 'ae2:item_storage_cell_256k',
    ingredients: [
      'ae2:item_cell_housing',
      'ae2:cell_component_256k',
    ] },
{ kind: 'shapeless', id: 'nekojs:ae2/fstoragecell1k_alt2',
    result: 'ae2:fluid_storage_cell_1k',
    ingredients: [
      'ae2:cell_component_1k',
      'ae2:fluid_cell_housing',
    ] },
{ kind: 'shapeless', id: 'nekojs:ae2/fstoragecell4k_alt2',
    result: 'ae2:fluid_storage_cell_4k',
    ingredients: [
      'ae2:cell_component_4k',
      'ae2:fluid_cell_housing',
    ] },
{ kind: 'shapeless', id: 'nekojs:ae2/fstoragecell16k_alt2',
    result: 'ae2:fluid_storage_cell_16k',
    ingredients: [
      'ae2:cell_component_16k',
      'ae2:fluid_cell_housing',
    ] },
{ kind: 'shapeless', id: 'nekojs:ae2/fstoragecell64k_alt2',
    result: 'ae2:fluid_storage_cell_64k',
    ingredients: [
      'ae2:cell_component_64k',
      'ae2:fluid_cell_housing',
    ] },
{ id: 'nekojs:ae2/fstoragecell256k',
    result: 'ae2:fluid_storage_cell_256k',
    pattern: ['ab ', 'cdc', 'ebe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:cell_component_256k',
      e: gt('screw', 'titanium'),
    } },
{ id: 'nekojs:ae2/storagecomponent1k',
    result: 'ae2:cell_component_1k',
    pattern: ['aba', 'cdc', 'aca'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:logic_processor',
      c: 'ae2:certus_quartz_crystal',
      d: 'ae2:quartz_glass',
    } },
{ id: 'nekojs:ae2/storagecomponent4k',
    result: 'ae2:cell_component_4k',
    pattern: ['aba', 'cdc', 'aca'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:calculation_processor',
      c: 'ae2:cell_component_1k',
      d: 'ae2:quartz_glass',
    } },
{ id: 'nekojs:ae2/storagecomponent16k',
    result: 'ae2:cell_component_16k',
    pattern: ['aba', 'cdc', 'aca'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:calculation_processor',
      c: 'ae2:cell_component_4k',
      d: 'ae2:quartz_glass',
    } },
{ id: 'nekojs:ae2/storagecomponent64k',
    result: 'ae2:cell_component_64k',
    pattern: ['aba', 'cdc', 'aca'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:calculation_processor',
      c: 'ae2:cell_component_16k',
      d: 'ae2:quartz_glass',
    } },
{ id: 'nekojs:ae2/storagecomponent256k',
    result: 'ae2:cell_component_256k',
    pattern: ['aba', 'cdc', 'aca'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:engineering_processor',
      c: 'ae2:cell_component_64k',
      d: 'ae2:quartz_glass',
    } },
{ id: 'nekojs:ae2/viewcell',
    result: 'ae2:view_cell',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'stainlesssteel'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:certus_quartz_crystal',
      e: gt('screw', 'stainlesssteel'),
      f: gt('casingSmall', 'stainlesssteel'),
    } },
{ id: 'nekojs:ae2/storagehousing',
    result: 'ae2:item_cell_housing',
    pattern: ['ab ', 'c c', 'ded'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: gt('screw', 'titanium'),
      e: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/spatialcomponent2',
    result: 'ae2:spatial_cell_component_2',
    pattern: ['aba', 'bcb', 'aba'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:fluix_pearl',
      c: 'ae2:engineering_processor',
    } },
{ id: 'nekojs:ae2/spatialcomponent16',
    result: 'ae2:spatial_cell_component_16',
    pattern: ['aba', 'bcb', 'aba'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:spatial_cell_component_2',
      c: 'ae2:engineering_processor',
    } },
{ id: 'nekojs:ae2/spatialcomponent128',
    result: 'ae2:spatial_cell_component_128',
    pattern: ['aba', 'bcb', 'aba'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:spatial_cell_component_16',
      c: 'ae2:engineering_processor',
    } },
{ id: 'nekojs:ae2/spatialcell2',
    result: 'ae2:spatial_storage_cell_2',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:spatial_cell_component_2',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/spatialcell16',
    result: 'ae2:spatial_storage_cell_16',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:spatial_cell_component_16',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/spatialcell128',
    result: 'ae2:spatial_storage_cell_128',
    pattern: ['ab ', 'cdc', 'efe'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: 'ae2:spatial_cell_component_128',
      e: gt('screw', 'titanium'),
      f: gt('casingSmall', 'titanium'),
    } },
{ id: 'nekojs:ae2/portablefluidcell',
    result: 'ae2:portable_fluid_cell_1k',
    pattern: ['ab ', 'cdc', ' ef'],
    keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:fluid_storage_cell_1k',
      c: gt('screw', 'titanium'),
      d: 'ae2:me_chest',
      e: 'ae2:energy_cell',
      f: gt('screw', 'steel'),
    } },
{ id: 'nekojs:ae2/advancedfluidstoragehousing',
    result: 'ae2:fluid_cell_housing',
    pattern: ['ab ', 'c c', 'dbd'],
    keys: {
      a: gt('screw', 'steel'),
      b: gt('plate', 'titanium'),
      c: gt('dust', 'redalloy'),
      d: gt('screw', 'titanium'),
    } },
{ id: 'nekojs:ae2/certusqknife',
      result: 'ae2:certus_quartz_cutting_knife',
      pattern: ['fga', 'bch', 'fjk'],
      keys: {
      a: 'minecraft:stick',
      b: gt('plate', 'steel'),
      c: gt('stick', 'iron'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12021),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      j: gtBlock('machineCasing', 'aluminium'),
      k: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      } },
{ id: 'nekojs:ae2/netherqknife',
      result: 'ae2:nether_quartz_cutting_knife',
      pattern: ['fga', 'bch', 'kjl'],
      keys: {
      a: 'minecraft:stick',
      b: gt('plate', 'steel'),
      c: gt('stick', 'iron'),
      f: gtIngredient('gregtech:gt.multiitem.technological', 12021),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12061),
      j: gtBlock('machineCasing', 'aluminium'),
      k: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      l: gtIngredient('gregtech:gt.multiitem.technological', 12141),
      } },
{ id: 'nekojs:ae2/wirelessterminal',
      result: 'ae2:wireless_terminal',
      pattern: ['abc', 'cde', 'hgi'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:wireless_receiver',
      c: gt('screw', 'titanium'),
      d: 'ae2:terminal',
      e: 'ae2:dense_energy_cell',
      g: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12144),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12124),
      } },
{ id: 'nekojs:ae2/wirelessbooster',
      result: 'ae2:wireless_booster', count: 2,
      pattern: [' ab', 'bcd', 'gfh'],
      keys: {
      a: 'ae2:fluix_pearl',
      b: gt('screw', 'titanium'),
      c: gt('casingSmall', 'titanium'),
      d: gt('screw', 'steel'),
      f: gtBlock('machineCasing', 'titanium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12044),
      } },
{ id: 'nekojs:ae2/basiccard',
    result: 'ae2:basic_card', count: 2,
    pattern: [' ab', 'cdc', 'bce'],
    keys: {
      a: 'ae2:calculation_processor',
      b: gt('screw', 'aluminium'),
      c: gt('plate', 'plastic'),
      d: gt('casingSmall', 'aluminium'),
      e: gt('screw', 'steel'),
    } },
{ id: 'nekojs:ae2/advancedcard',
    result: 'ae2:advanced_card', count: 2,
    pattern: [' ab', 'cdc', 'bef'],
    keys: {
      a: 'ae2:calculation_processor',
      b: gt('screw', 'tungsten'),
      c: gt('plate', 'plastic'),
      d: gt('casingSmall', 'tungsten'),
      e: gt('plate', 'diamond'),
      f: gt('screw', 'steel'),
    } },
{ id: 'nekojs:ae2/memorycard',
    result: 'ae2:memory_card',
    pattern: ['abb', 'cdc', '   '],
    keys: {
      a: 'ae2:calculation_processor',
      b: gt('plate', 'plastic'),
      c: gt('wire', 'gold'),
      d: gt('dust', 'redalloy'),
    } },
{ id: 'nekojs:ae2/redstonecard',
    result: 'ae2:redstone_card',
    pattern: ['ab', 'bc'],
    keys: {
      a: 'ae2:basic_card',
      b: 'minecraft:redstone_torch',
      c: 'ae2:calculation_processor',
    } },
{ id: 'nekojs:ae2/capacitycard',
    result: 'ae2:capacity_card',
    pattern: ['ab', 'bc'],
    keys: {
      a: 'ae2:basic_card',
      b: 'ae2:certus_quartz_crystal',
      c: 'ae2:cell_component_1k',
    } },
{ id: 'nekojs:ae2/craftingcard',
    result: 'ae2:crafting_card',
    pattern: ['ab', 'cd'],
    keys: {
      a: 'ae2:basic_card',
      b: gt('screw', 'steel'),
      c: gt('screw', 'titanium'),
      d: 'minecraft:crafting_table',
    } },
{ id: 'nekojs:ae2/accelerationcard',
    result: 'ae2:speed_card',
    pattern: ['ab', 'bc'],
    keys: {
      a: 'ae2:advanced_card',
      b: 'ae2:fluix_crystal',
      c: 'ae2:calculation_processor',
    } },
{ id: 'nekojs:ae2/invertercard',
    result: 'ae2:inverter_card',
    pattern: ['ab', 'bc'],
    keys: {
      a: 'ae2:advanced_card',
      b: 'minecraft:redstone_torch',
      c: 'ae2:calculation_processor',
    } },
{ id: 'nekojs:ae2/formationcore',
    result: 'ae2:formation_core', count: 2,
    pattern: ['aba', 'cdc', 'aba'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'ae2:certus_quartz_crystal',
      c: 'ae2:fluix_dust',
      d: 'ae2:logic_processor',
    } },
{ id: 'nekojs:ae2/annihilationcore',
    result: 'ae2:annihilation_core', count: 2,
    pattern: ['aba', 'cdc', 'aba'],
    keys: {
      a: gt('dust', 'redalloy'),
      b: 'minecraft:quartz',
      c: 'ae2:fluix_dust',
      d: 'ae2:logic_processor',
    } },
{ id: 'nekojs:ae2/wirelessreceiver',
      result: 'ae2:wireless_receiver',
      pattern: ['bad', 'bcb', 'gfh'],
      keys: {
      a: 'ae2:fluix_pearl',
      b: gt('plateCurved', 'stainlesssteel'),
      c: gt('wire', 'copper', 2),
      d: gt('gem', 'certusquartz'),
      f: gtBlock('machineCasing', 'stainlesssteel'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12003),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12043),
      } },
{ id: 'nekojs:ae2/certusquartztank',
      result: 'ae2:quartz_glass',
      pattern: ['aaa', 'aaa', 'gfh'],
      keys: {
      a: 'ae2:quartz_glass',
      f: gtBlock('machineCasing', 'aluminium'),
      g: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12041),
      } },
{ id: 'nekojs:ae2/ingredientbuffer',
      result: 'extendedae:ingredient_buffer',
      pattern: ['aba', 'cde', 'hgi'],
      keys: {
      a: gt('plate', 'titanium'),
      b: 'ae2:cell_component_1k',
      c: 'ae2:annihilation_core',
      d: 'ae2:interface',
      e: 'ae2:formation_core',
      g: gtBlock('machineCasing', 'titanium'),
      h: gtIngredient('gregtech:gt.multiitem.technological', 12004),
      i: gtIngredient('gregtech:gt.multiitem.technological', 12044),
      } },
{ id: 'nekojs:ae2/universalwirelessterminal',
      result: 'ae2wtlib:wireless_universal_terminal',
      pattern: ['abc', 'def', 'jik'],
      keys: {
      a: gt('screw', 'steel'),
      b: 'ae2:wireless_terminal',
      c: gt('screw', 'tungsten'),
      d: 'ae2:wireless_terminal',
      e: gt('wire', 'platinum'),
      f: 'ae2:wireless_terminal',
      i: gtBlock('machineCasing', 'tungsten'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12145),
      k: gtIngredient('gregtech:gt.multiitem.technological', 12125),
      } },
{ id: 'nekojs:ae2/cable_anchor',
      result: 'ae2:cable_anchor',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/cable_bus',
      result: 'ae2:cable_bus',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/cable_energy_acceptor',
      result: 'ae2:cable_energy_acceptor',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/crafting_pattern',
      result: 'ae2:crafting_pattern',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:blank_pattern',
      f: 'ae2:calculation_processor',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/crank',
      result: 'ae2:crank',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/crystal_resonance_generator',
      result: 'ae2:crystal_resonance_generator',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:energy_cell',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/dark_monitor',
      result: 'ae2:dark_monitor',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/energy_level_emitter',
      result: 'ae2:energy_level_emitter',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/fe_p2p_tunnel',
      result: 'ae2:fe_p2p_tunnel',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:me_p2p_tunnel',
      f: 'ae2:fluix_crystal',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/fluid_p2p_tunnel',
      result: 'ae2:fluid_p2p_tunnel',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:me_p2p_tunnel',
      f: 'ae2:fluix_crystal',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/fluix_upgrade_smithing_template',
      result: 'ae2:fluix_upgrade_smithing_template',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/fuzzy_card',
      result: 'ae2:fuzzy_card',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:basic_card',
      f: 'ae2:calculation_processor',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/growth_accelerator',
      result: 'ae2:growth_accelerator',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/inscriber',
      result: 'ae2:inscriber',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:energy_cell',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/inverted_toggle_bus',
      result: 'ae2:inverted_toggle_bus',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:basic_card',
      f: 'ae2:calculation_processor',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/item_p2p_tunnel',
      result: 'ae2:item_p2p_tunnel',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:me_p2p_tunnel',
      f: 'ae2:fluix_crystal',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/light_p2p_tunnel',
      result: 'ae2:light_p2p_tunnel',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:me_p2p_tunnel',
      f: 'ae2:fluix_crystal',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/matrix_frame',
      result: 'ae2:matrix_frame',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:engineering_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:energy_cell',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/monitor',
      result: 'ae2:monitor',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:fluix_crystal',
      f: 'ae2:quartz_glass',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/processing_pattern',
      result: 'ae2:processing_pattern',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:blank_pattern',
      f: 'ae2:calculation_processor',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
{ id: 'nekojs:ae2/redstone_p2p_tunnel',
      result: 'ae2:redstone_p2p_tunnel',
      pattern: ['aba', 'cef', 'idj'],
      keys: {
      a: gt('screw', 'aluminium'),
      b: 'ae2:logic_processor',
      c: 'ae2:quartz_glass',
      e: 'ae2:me_p2p_tunnel',
      f: 'ae2:fluix_crystal',
      i: gtIngredient('gregtech:gt.multiitem.technological', 12001),
      d: gtBlock('machineCasing', 'aluminium'),
      j: gtIngredient('gregtech:gt.multiitem.technological', 12081),
      } },
]

function splitPath(path) {
  const text = String(path)
  const parts = []
  let buffer = ''
  for (let index = 0; index < text.length; index++) {
    const ch = text.charAt(index)
    if (ch === '.') {
      parts.push(buffer)
      buffer = ''
      continue
    }
    if (ch === '[') {
      if (buffer.length > 0) {
        parts.push(buffer)
        buffer = ''
      }
      let digits = ''
      index++
      while (index < text.length && text.charAt(index) !== ']') {
        digits = digits + text.charAt(index)
        index++
      }
      parts.push(digits)
      continue
    }
    buffer = buffer + ch
  }
  if (buffer.length > 0) {
    parts.push(buffer)
  }
  return parts
}

function readJsonPath(object, path) {
  let current = object
  for (const part of splitPath(path)) {
    if (current == null || typeof current !== 'object') return undefined
    current = current[part]
  }
  return current
}

function applyOne(event, id, path, value) {
  let entry = null
  try {
    entry = event.get(id)
  } catch (getError) {
    return false
  }
  try {
    entry.setPath(path, value)
  } catch (setPathError) {
  }
  let stored = null
  try {
    stored = JSON.parse(event.getJson(id))
  } catch (readError) {
    stored = null
  }
  if (stored == null) return false
  const parts = splitPath(path)
  let cursor = stored
  for (let index = 0; index < parts.length - 1; index++) {
    if (cursor[parts[index]] == null) cursor[parts[index]] = {}
    cursor = cursor[parts[index]]
  }
  cursor[parts[parts.length - 1]] = value
  event.setJson(id, JSON.stringify(stored))
  return JSON.stringify(readJsonPath(JSON.parse(event.getJson(id)), path)) === JSON.stringify(value)
}

function toIngredient(value) {
  return value
}

function toResult(recipe) {
  return recipe.count === undefined ? { id: recipe.result } : { id: recipe.result, count: recipe.count }
}

function buildRecipeJson(recipe) {
  if (recipe.kind === undefined || recipe.kind === 'shaped') {
    const key = {}
    for (const [letter, value] of Object.entries(recipe.keys)) {
      key[letter] = toIngredient(value)
    }
    return JSON.stringify({
      type: 'minecraft:crafting_shaped',
      pattern: recipe.pattern,
      key: key,
      result: toResult(recipe)
    })
  }
  if (recipe.kind === 'shapeless') {
    return JSON.stringify({
      type: 'minecraft:crafting_shapeless',
      ingredients: recipe.ingredients.map(toIngredient),
      result: toResult(recipe)
    })
  }
  throw new Error('未知的配方类型：' + String(recipe.kind))
}

function addDesigned(event, recipe) {
  const jsonText = buildRecipeJson(recipe)
  event.shaped(Item.of('minecraft:stone'), ['S'], { S: 'minecraft:stone' }).id(recipe.id)
  event.setJson(recipe.id, jsonText)
  const readBack = JSON.parse(event.getJson(recipe.id))
  if (JSON.stringify(readBack) !== JSON.stringify(JSON.parse(jsonText))) {
    throw new Error('配方 JSON 写入后读回不一致：' + recipe.id)
  }
}

ServerEvents.recipes(event => {
  const problems = []
  let removedCount = 0
  for (const removeId of REMOVE) {
    if (!event.exists(removeId)) {
      continue
    }
    try {
      event.get(removeId).remove()
      removedCount = removedCount + 1
    } catch (removeError) {
      problems.push(removeId + ' 删除失败：' + String(removeError))
    }
  }
  let addedCount = 0
  const touchedIds = new Set()
  for (const recipe of RECIPES) {
    try {
      addDesigned(event, recipe)
      addedCount = addedCount + 1
      touchedIds.add(recipe.id)
    } catch (addError) {
      problems.push(recipe.id + ' 注册失败：' + String(addError))
    }
  }
  let modernizedCount = 0
  for (const touchedId of touchedIds) {
    try {
      if (modernizeRecipe(event, touchedId)) {
        modernizedCount = modernizedCount + 1
      }
    } catch (modernizeError) {
      problems.push(touchedId + ' 成分写法转换失败：' + String(modernizeError))
    }
  }
  console.info(
    '[NekoJS/AE2] 参考重构：删 ' + removedCount + '/' + REMOVE.length + ' 条原配方；新增 ' + addedCount + '/' + RECIPES.length + ' 条；成分写法现代化 ' + modernizedCount + ' 条；问题 ' + problems.length + ' 处。'
  )
  if (problems.length > 0) {
    console.warn('[NekoJS/AE2] 未完成：' + problems.join(' | '))
  }
})
