import { applyReforge } from '../src/lib/gt6_reforge.js'

const REMOVE = [
  'enderio:conductive_alloy_ingot',
  'enderio:dark_steel_ingot',
  'enderio:end_steel_ingot',
  'enderio:energetic_alloy_ingot',
  'enderio:item.enderio.conductive_alloy_nugget_to_ingot',
  'enderio:item.enderio.dark_steel_nugget_to_ingot',
  'enderio:item.enderio.end_steel_nugget_to_ingot',
  'enderio:item.enderio.energetic_alloy_nugget_to_ingot',
  'enderio:item.enderio.pulsating_alloy_nugget_to_ingot',
  'enderio:item.enderio.redstone_alloy_nugget_to_ingot',
  'enderio:item.enderio.soularium_nugget_to_ingot',
  'enderio:item.enderio.vibrant_alloy_nugget_to_ingot',
  'enderio:pulsating_alloy_ingot',
  'enderio:redstone_alloy_ingot',
  'enderio:soularium_ingot',
  'enderio:vibrant_alloy_ingot',
  'extendedae:transform/entro_ingot',
  'mmcr:modularium',
  'minecraft:lead_ingot_from_blasting_deepslate_lead_ore',
  'minecraft:lead_ingot_from_blasting_lead_ore',
  'minecraft:lead_ingot_from_blasting_lead_raw',
  'minecraft:lead_ingot_from_smelting_deepslate_lead_ore',
  'minecraft:lead_ingot_from_smelting_lead_ore',
  'minecraft:lead_ingot_from_smelting_lead_raw',
  'minecraft:nickel_ingot_from_blasting_deepslate_nickel_ore',
  'minecraft:nickel_ingot_from_blasting_nickel_ore',
  'minecraft:nickel_ingot_from_blasting_nickel_raw',
  'minecraft:nickel_ingot_from_smelting_deepslate_nickel_ore',
  'minecraft:nickel_ingot_from_smelting_nickel_ore',
  'minecraft:nickel_ingot_from_smelting_nickel_raw',
  'minecraft:silver_ingot_from_blasting_deepslate_silver_ore',
  'minecraft:silver_ingot_from_blasting_silver_ore',
  'minecraft:silver_ingot_from_blasting_silver_raw',
  'minecraft:silver_ingot_from_smelting_deepslate_silver_ore',
  'minecraft:silver_ingot_from_smelting_silver_ore',
  'minecraft:silver_ingot_from_smelting_silver_raw',
  'minecraft:tin_ingot_from_blasting_deepslate_tin_ore',
  'minecraft:tin_ingot_from_blasting_tin_ore',
  'minecraft:tin_ingot_from_blasting_tin_raw',
  'minecraft:tin_ingot_from_smelting_deepslate_tin_ore',
  'minecraft:tin_ingot_from_smelting_tin_ore',
  'minecraft:tin_ingot_from_smelting_tin_raw',
  'minecraft:zinc_ingot_from_blasting_deepslate_zinc_ore',
  'minecraft:zinc_ingot_from_blasting_zinc_ore',
  'minecraft:zinc_ingot_from_blasting_zinc_raw',
  'minecraft:zinc_ingot_from_smelting_deepslate_zinc_ore',
  'minecraft:zinc_ingot_from_smelting_zinc_ore',
  'minecraft:zinc_ingot_from_smelting_zinc_raw',
]

ServerEvents.recipes(event => {
  applyReforge(event, { tag: 'NoOtherIngots', remove: REMOVE, edits: [], gates: [], add: [] })
})
