; {"groups":{"0":{"viewmode":"DEFAULT","crafting":false,"collapsed":false}}}
{"item":{"Count":0,"Damage":1,"strId":"ExtraPlanets:tile.advancedLaunchPad"},"multiplier":0,"factor":1,"type":0}
; {"groups":{"0":{"viewmode":"DEFAULT","crafting":false,"collapsed":false}}}
