#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri Oct 02 22:22:44 GMT+08:00 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=
