
import { RF, applyReforge } from '../src/lib/gt6_reforge.js'

const REMOVE = [
]

const EDITS = [
  { id: 'sophisticatedstorage:advanced_alchemy_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_compacting_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_feeding_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_filter_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_hopper_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_jukebox_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_magnet_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:advanced_magnet_upgrade_from_basic', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_pickup_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:advanced_void_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:alchemy_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:auto_blasting_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:auto_blasting_upgrade_from_auto_smelting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:auto_smelting_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:auto_smoking_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:basic_to_copper_tier_upgrade', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:basic_to_gold_tier_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:basic_to_iron_tier_from_basic_to_copper_tier', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:basic_to_iron_tier_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:blasting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:blasting_upgrade_from_smelting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:compacting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:compression_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:copper_barrel', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:copper_chest', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:copper_shulker_box', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:copper_to_gold_tier_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:copper_to_iron_tier_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:crafting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:double_copper_chest', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:double_gold_chest', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:double_iron_chest', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:double_iron_chest_from_copper_chest', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:gold_barrel', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:gold_chest', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:gold_shulker_box', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:hopper_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_barrel', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_barrel_from_copper_barrel', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_chest', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_chest_from_copper_chest', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_shulker_box', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_shulker_box_from_copper_shulker_box', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:iron_to_gold_tier_upgrade', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:jukebox_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:limited_copper_barrel_1', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:limited_copper_barrel_2', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:limited_copper_barrel_3', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:limited_copper_barrel_4', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:limited_gold_barrel_1', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:limited_gold_barrel_2', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:limited_gold_barrel_3', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:limited_gold_barrel_4', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:limited_iron_barrel_1', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:limited_iron_barrel_1_from_limited_copper_barrel_1',
    path: 'key.I',
    value: RF.steel_plate
  },
  { id: 'sophisticatedstorage:limited_iron_barrel_2', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:limited_iron_barrel_2_from_limited_copper_barrel_2',
    path: 'key.I',
    value: RF.steel_plate
  },
  { id: 'sophisticatedstorage:limited_iron_barrel_3', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:limited_iron_barrel_3_from_limited_copper_barrel_3',
    path: 'key.I',
    value: RF.steel_plate
  },
  { id: 'sophisticatedstorage:limited_iron_barrel_4', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:limited_iron_barrel_4_from_limited_copper_barrel_4',
    path: 'key.I',
    value: RF.steel_plate
  },
  { id: 'sophisticatedstorage:magnet_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:smelting_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:smoking_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_2_conversion', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_3_conversion', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_1_plus_conversion', path: 'key.C', value: RF.copper_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_2_conversion', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_3_conversion', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_from_tier_1_plus', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_3_conversion', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:stonecutter_upgrade', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:storage_input', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:storage_io', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:storage_output', path: 'key.G', value: RF.gold_plate },
  { id: 'sophisticatedstorage:storage_tool', path: 'key.I', value: RF.steel_plate },
  { id: 'sophisticatedstorage:upgrade_base', path: 'key.I', value: RF.steel_plate },
]

const GATES = [
  { id: 'sophisticatedstorage:backpack_stack_upgrade_omega_tier_from_storage_stack_upgrade_omega_tier',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_omega_tier_from_storage_stack_upgrade_omega_tier',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_starter_tier_from_storage_stack_upgrade_tier_1_plus',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_starter_tier_from_storage_stack_upgrade_tier_1_plus',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_1_from_storage_stack_upgrade_tier_2',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_1_from_storage_stack_upgrade_tier_2',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_2_from_storage_stack_upgrade_tier_3',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_2_from_storage_stack_upgrade_tier_3',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_3_from_storage_stack_upgrade_tier_4',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_3_from_storage_stack_upgrade_tier_4',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_4_from_storage_stack_upgrade_tier_5',
    path: 'pattern',
    value: [' ST', 'SLS', 'TZT']
  },
  { id: 'sophisticatedstorage:backpack_stack_upgrade_tier_4_from_storage_stack_upgrade_tier_5',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:basic_tier_upgrade', path: 'pattern', value: [' S ', 'SLS', ' Z '] },
  { id: 'sophisticatedstorage:basic_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_copper_tier_upgrade', path: 'pattern', value: ['CCC', 'CLC', 'CZC'] },
  { id: 'sophisticatedstorage:basic_to_copper_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_diamond_tier_upgrade', path: 'pattern', value: ['DDD', 'DTD', 'DZD'] },
  { id: 'sophisticatedstorage:basic_to_diamond_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_gold_tier_upgrade', path: 'pattern', value: ['GGG', 'GTG', 'GZG'] },
  { id: 'sophisticatedstorage:basic_to_gold_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_iron_tier_from_basic_to_copper_tier',
    path: 'pattern',
    value: [' I ', 'IRI', ' Z ']
  },
  { id: 'sophisticatedstorage:basic_to_iron_tier_from_basic_to_copper_tier', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_iron_tier_upgrade', path: 'pattern', value: ['III', 'ILI', 'IZI'] },
  { id: 'sophisticatedstorage:basic_to_iron_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:basic_to_netherite_tier_upgrade', path: 'ingredients[2]', value: RF.steel_screw },
  { id: 'sophisticatedstorage:copper_to_diamond_tier_upgrade', path: 'pattern', value: ['DDD', 'DTD', 'DZD'] },
  { id: 'sophisticatedstorage:copper_to_diamond_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:copper_to_gold_tier_upgrade', path: 'pattern', value: ['GGG', 'GTG', 'GZG'] },
  { id: 'sophisticatedstorage:copper_to_gold_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:copper_to_iron_tier_upgrade', path: 'pattern', value: [' I ', 'ILI', ' Z '] },
  { id: 'sophisticatedstorage:copper_to_iron_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:copper_to_netherite_tier_upgrade', path: 'ingredients[2]', value: RF.steel_screw },
  { id: 'sophisticatedstorage:diamond_to_netherite_tier_upgrade', path: 'ingredients[2]', value: RF.steel_screw },
  { id: 'sophisticatedstorage:gold_to_diamond_tier_upgrade', path: 'pattern', value: ['DDD', 'DLD', 'DZD'] },
  { id: 'sophisticatedstorage:gold_to_diamond_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:gold_to_netherite_tier_upgrade', path: 'ingredients[2]', value: RF.steel_screw },
  { id: 'sophisticatedstorage:iron_to_diamond_tier_upgrade', path: 'pattern', value: ['DDD', 'DTD', 'DZD'] },
  { id: 'sophisticatedstorage:iron_to_diamond_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:iron_to_gold_tier_upgrade', path: 'pattern', value: ['GGG', 'GLG', 'GZG'] },
  { id: 'sophisticatedstorage:iron_to_gold_tier_upgrade', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:iron_to_netherite_tier_upgrade', path: 'ingredients[2]', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_omega_tier', path: 'pattern', value: ['SSS', 'SSS', 'SZS'] },
  { id: 'sophisticatedstorage:stack_upgrade_omega_tier', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1', path: 'pattern', value: ['LLL', 'LBL', 'LZL'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus', path: 'pattern', value: ['CCC', 'CSC', 'BZB'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_2_conversion',
    path: 'pattern',
    value: [' I ', 'IPI', ' Z ']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_2_conversion',
    path: 'key',
    value: { "I": RF.steel_plate,
      "P": "#minecraft:planks",
      "Z": RF.steel_screw
    }
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_3_conversion',
    path: 'pattern',
    value: ['GGG', 'GSG', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_3_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_4_conversion',
    path: 'pattern',
    value: ['DDD', 'DSD', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_4_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_5_conversion',
    path: 'pattern',
    value: ['NNN', 'NSN', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_plus_to_tier_5_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_1_plus_conversion',
    path: 'pattern',
    value: ['CCC', 'CPC', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_1_plus_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_2_conversion',
    path: 'pattern',
    value: ['III', 'ISI', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_2_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_3_conversion',
    path: 'pattern',
    value: ['GGG', 'GSG', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_3_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_4_conversion',
    path: 'pattern',
    value: ['DDD', 'DSD', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_4_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_5_conversion',
    path: 'pattern',
    value: ['NNN', 'NSN', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_1_to_tier_5_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2', path: 'pattern', value: ['III', 'ISI', 'BZB'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_from_tier_1_plus', path: 'pattern', value: [' I ', 'ISI', ' Z '] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_from_tier_1_plus',
    path: 'key',
    value: { "I": RF.steel_plate,
      "S": "sophisticatedstorage:stack_upgrade_tier_1_plus",
      "Z": RF.steel_screw
    }
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_3_conversion',
    path: 'pattern',
    value: ['GGG', 'GPG', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_3_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_4_conversion',
    path: 'pattern',
    value: ['DDD', 'DSD', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_4_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_5_conversion',
    path: 'pattern',
    value: ['NNN', 'NSN', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_2_to_tier_5_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3', path: 'pattern', value: ['GGG', 'GSG', 'BZB'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3_to_tier_4_conversion',
    path: 'pattern',
    value: ['DDD', 'DPD', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3_to_tier_4_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3_to_tier_5_conversion',
    path: 'pattern',
    value: ['NNN', 'NSN', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_3_to_tier_5_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_4', path: 'pattern', value: ['DDD', 'DSD', 'BZB'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_4', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_4_to_tier_5_conversion',
    path: 'pattern',
    value: ['NNN', 'NPN', 'BZB']
  },
  { id: 'sophisticatedstorage:stack_upgrade_tier_4_to_tier_5_conversion', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:stack_upgrade_tier_5', path: 'pattern', value: ['NNN', 'NSN', 'BZB'] },
  { id: 'sophisticatedstorage:stack_upgrade_tier_5', path: 'key.Z', value: RF.steel_screw },
  { id: 'sophisticatedstorage:storage_stack_upgrade_omega_tier_from_backpack_stack_upgrade_omega_tier',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_omega_tier_from_backpack_stack_upgrade_omega_tier',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_1_plus_from_backpack_stack_upgrade_starter_tier',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_1_plus_from_backpack_stack_upgrade_starter_tier',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_2_from_backpack_stack_upgrade_tier_1',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_2_from_backpack_stack_upgrade_tier_1',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_3_from_backpack_stack_upgrade_tier_2',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_3_from_backpack_stack_upgrade_tier_2',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_4_from_backpack_stack_upgrade_tier_3',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_4_from_backpack_stack_upgrade_tier_3',
    path: 'key.Z',
    value: RF.steel_screw
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_5_from_backpack_stack_upgrade_tier_4',
    path: 'pattern',
    value: [' SP', ' P ', 'PZP']
  },
  { id: 'sophisticatedstorage:storage_stack_upgrade_tier_5_from_backpack_stack_upgrade_tier_4',
    path: 'key.Z',
    value: RF.steel_screw
  },
]

const ADD = []

ServerEvents.recipes(event => {
  applyReforge(event, { tag: 'Storage', remove: REMOVE, edits: EDITS, gates: GATES, add: ADD })
})
