# Configuration file

general {
    # Global ID Biome for Planets/Moons
    I:IDSpaceBiome=2200
    # Global ID Biome for Planets/Moons (Shallow Waters Biome)
    I:IDSpaceShallowWatersBiome=2201
    # Global ID Biome for Planets/Moons (Oceans Biome)
    I:IDSpaceOceansBiome=2202
    # Global ID Biome for Planets/Moons (Deep Oceans Biome)
    I:IDSpaceDeepOceansBiome=2203
    # Global ID Biome for Planets/Moons (Low Plains Biome)
    I:IDSpaceLowPlainsBiome=2204
    # Global ID Biome for Planets/Moons (Mid Plains Biome)
    I:IDSpaceMidPlainsBiome=2205
    # Global ID Biome for Planets/Moons (Low Hills Biome)
    I:IDSpaceLowHillsBiome=2206
    # Global ID Biome for Planets/Moons (High Plateaus Biome)
    I:IDSpaceHighPlateausBiome=2207
    # Global ID Biome for Planets/Moons (Mid Hills Biome)
    I:IDSpaceMidHillsBiome=2208
    # Global ID Biome for Planets/Moons (Rocky Waters Biome)
    I:IDSpaceRockyWatersBiome=2209
    # Global ID Biome for Planets/Moons (Low Islands Biome)
    I:IDSpaceLowIslandsBiome=2210
    # Global ID Biome for Planets/Moons (Partially Submerged Biome)
    I:IDSpacePartiallySubmergedBiome=2211
    # Global ID Biome for Planets/Moons (Beach Biome)
    I:IDSpaceBeachBiome=2212
    # Biome ID for World Engine
    I:IDWorldEngineBiome=2213
}


