
import { RF, applyReforge } from '../src/lib/gt6_reforge.js'

const REMOVE = [
]

const EDITS = [
  { id: 'enderio:alloy_smelter', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:alloy_smelter', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:alloy_smelter', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:attractor_obelisk', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:aversion_obelisk', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:basic_capacitor', path: 'key.I', value: RF.copper_plate },
  { id: 'enderio:crafter', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:crafter', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:crafter', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:dark_bimetal_gear', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:drain', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:drain', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:energetic_photovoltaic_module', path: 'key.E', value: RF.gold_plate },
  { id: 'enderio:energized_gear', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:farming_station', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:fluid_tank', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:impulse_hopper', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:impulse_hopper', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:inhibitor_obelisk', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:inhibitor_obelisk', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:iron_gear', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:niard', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:painting_machine', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:painting_machine', path: 'key.M', value: RF.iron_gear },
  { id: 'enderio:powered_spawner', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:redstone_filter_base', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:sag_mill', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:sag_mill', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:sag_mill', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:slice_and_splice', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:soul_binder', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:soul_engine', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:stirling_generator', path: 'key.G', value: RF.iron_gear },
  { id: 'enderio:stirling_generator', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:stirling_generator', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:travel_anchor', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:vacuum_chest', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:vat', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:vat', path: 'key.M', value: RF.iron_gear },
  { id: 'enderio:void_chassis', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:weather_obelisk', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:wired_charger', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:wireless_charger', path: 'key.V', value: RF.casingT0 },
  { id: 'enderio:xp_obelisk', path: 'key.C', value: RF.casingT0 },
  { id: 'enderio:xp_vacuum', path: 'key.I', value: RF.steel_plate },
  { id: 'enderio:yeta_wrench', path: 'key.I', value: RF.copper_plate },
]

const GATES = [
  { id: 'enderio:alloy_smelter', path: 'pattern', value: ['GFG', 'FVF', 'IZI'] },
  { id: 'enderio:alloy_smelter',
    path: 'key',
    value: { "F": "minecraft:furnace",
      "G": RF.iron_gear,
      "I": RF.steel_plate,
      "V": RF.casingT0,
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:crafter', path: 'pattern', value: ['TSS', 'ICI', 'GZG'] },
  { id: 'enderio:crafter', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:drain', path: 'pattern', value: ['BCI', 'IVI', 'GZG'] },
  { id: 'enderio:drain', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:enchanter', path: 'pattern', value: [' B ', 'DLD', 'IZI'] },
  { id: 'enderio:enchanter', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:energetic_photovoltaic_module', path: 'pattern', value: ['EFE', 'PPP', 'CZC'] },
  { id: 'enderio:energetic_photovoltaic_module',
    path: 'key',
    value: { "C": "enderio:basic_capacitor",
      "E": RF.gold_plate,
      "F": "#c:glass_blocks",
      "P": "enderio:photovoltaic_plate",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:erase_alloy_smelter', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_attractor_obelisk', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_aversion_obelisk', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_crafter', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_drain', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_energetic_photovoltaic_module', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_fluid_tank', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_impulse_hopper', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_inhibitor_obelisk', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_painting_machine', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_pressurized_fluid_tank', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_pulsating_photovoltaic_module', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_relocator_obelisk', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_sag_mill', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_soul_binder', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_stirling_generator', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_vacuum_chest', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_vibrant_photovoltaic_module', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_xp_obelisk', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:erase_xp_vacuum', path: 'ingredients[1]', value: RF.casingT0 },
  { id: 'enderio:fluid_tank', path: 'pattern', value: ['IBI', 'BGB', 'IZI'] },
  { id: 'enderio:fluid_tank', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:impulse_hopper', path: 'pattern', value: ['IHI', 'GCG', 'IZI'] },
  { id: 'enderio:impulse_hopper',
    path: 'key',
    value: { "C": RF.casingT0,
      "G": RF.iron_gear,
      "H": "minecraft:hopper",
      "I": "#c:ingots/conductive_alloy",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:painting_machine', path: 'pattern', value: ['RGB', 'ICI', 'MZM'] },
  { id: 'enderio:painting_machine',
    path: 'key',
    value: { "B": "#c:dyes/blue",
      "C": RF.casingT0,
      "G": "#c:dyes/green",
      "I": "#c:ingots/conductive_alloy",
      "M": RF.iron_gear,
      "R": "#c:dyes/red",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:photovoltaic_composite', path: 'ingredients[3]', value: RF.casingT0 },
  { id: 'enderio:pressurized_fluid_tank', path: 'pattern', value: ['IBI', 'BGB', 'IZI'] },
  { id: 'enderio:pressurized_fluid_tank', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:pulsating_photovoltaic_module', path: 'pattern', value: ['IFI', 'PDP', 'CZC'] },
  { id: 'enderio:pulsating_photovoltaic_module',
    path: 'key',
    value: { "C": "enderio:double_layer_capacitor",
      "D": "#c:dusts/coal",
      "F": "#c:glass_blocks/enlighted_fused_quartz",
      "I": "#c:ingots/pulsating_alloy",
      "P": "enderio:photovoltaic_plate",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:sag_mill', path: 'pattern', value: ['PFG', 'IVI', 'OZO'] },
  { id: 'enderio:sag_mill', path: 'key.Z', value: RF.casingT0 },
  { id: 'enderio:soul_binder', path: 'pattern', value: ['IVI', 'GCG', 'IYI'] },
  { id: 'enderio:soul_binder',
    path: 'key',
    value: { "C": RF.casingT0,
      "G": "#c:gears/energized",
      "I": "#c:ingots/soularium",
      "V": { "neoforge:ingredient_type":"enderio:empty_soul_storage",
        "item":"enderio:soul_vial"
      },
      "Y": RF.casingT0
    }
  },
  { id: 'enderio:stirling_generator', path: 'pattern', value: ['GFG', 'IVI', 'OZO'] },
  { id: 'enderio:stirling_generator',
    path: 'key',
    value: { "F": "minecraft:furnace",
      "G": RF.iron_gear,
      "I": RF.steel_plate,
      "O": "#c:obsidians",
      "V": RF.casingT0,
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:vacuum_chest', path: 'pattern', value: ['III', 'ICI', 'IZI'] },
  { id: 'enderio:vacuum_chest', path: 'key', value: { "C": "#c:chests", "I": RF.steel_plate, "Z": RF.casingT0 } },
  { id: 'enderio:vat', path: 'pattern', value: ['SBS', 'ACA', 'MZM'] },
  { id: 'enderio:vat',
    path: 'key',
    value: { "A": "#c:ingots/conductive_alloy",
      "B": "minecraft:barrel",
      "C": RF.casingT0,
      "M": RF.iron_gear,
      "S": "#c:ingots/dark_steel",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:vibrant_photovoltaic_module', path: 'pattern', value: ['IFI', 'PGP', 'CZC'] },
  { id: 'enderio:vibrant_photovoltaic_module',
    path: 'key',
    value: { "C": "enderio:octadic_capacitor",
      "F": "#c:glass_blocks/dark_fused_quartz",
      "G": "minecraft:glowstone",
      "I": "#c:ingots/vibrant_alloy",
      "P": "enderio:photovoltaic_plate",
      "Z": RF.casingT0
    }
  },
  { id: 'enderio:xp_vacuum', path: 'pattern', value: ['III', 'IRI', 'IZI'] },
  { id: 'enderio:xp_vacuum', path: 'key', value: { "I": RF.steel_plate, "R": "enderio:void_vial", "Z": RF.casingT0 } },
]

const ADD = []

ServerEvents.recipes(event => {
  applyReforge(event, { tag: 'EIO', remove: REMOVE, edits: EDITS, gates: GATES, add: ADD })
})
